### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by frietboer** [albedozero/squishbox#1]
when trying to run the 2.0 image, the following error occurs:

Traceback (most recent call last):
  File "squishbox.py", line 435, in <module>
    fluidsynth = importlib.import_module(config.get('fluidversion','fluidsynth'))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/fluidsynth-2_0_3.py", line 53, in <module>
    _fl = CDLL(lib)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/arm-linux-gnueabihf/libpulse.so.0: invalid ELF header

it seems that gnueabihf is compiled for the wrong processor? This error occurs on both the pi 2 and pi 3

**Comment by albedozero** [comment]
This may have been an issue with the particular Raspbian distribution used in the image. This repository has effectively been superseded by [fluidpatcher](https://github.com/albedozero/fluidpatcher), which now has its own [SD card image](https://github.com/albedozero/fluidpatcher/releases) that should hopefully fix the issue.
